### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by crigler** [google/werm#3]
This project is licensed under the Apache License version 2.0, however it includes code from my [dtach](https://github.com/crigler/dtach) project which is licensed under the GNU General Public License version 2.0. As [https://www.apache.org/licenses/GPL-compatibility.html](https://www.apache.org/licenses/GPL-compatibility.html) states:

> Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
>
> This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.
>
> We avoid GPLv3 software because merely linking to it is considered by the GPLv3 authors to create a derivative work. We want to honor their license. Unless GPLv3 licensors relax this interpretation of their own license regarding linking, our licensing philosophies are fundamentally incompatible. This is an identical issue for both GPLv2 and GPLv3.
>
> Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license. The Apache Software Foundation believes that you should always try to obey the constraints expressed by the copyright holder when redistributing their work.

**Comment by matvore** [comment]
I will update the Werm license and add dtach modification notes as required by GPLv2.

**Comment by matvore** [comment]
Re-licensed with BSD 3-clause. I believe the project is in compliance now.

**Comment by crigler** [comment]
Everyone downstream should be made aware that werm as a whole is licensed under the GPL since werm integrates dtach to handle terminal multiplexing. Even though the rest of the code may be under the BSD license:

> 2b) You must cause any work that you distribute or publish, that in
> whole or in part contains or is derived from the Program or any
> part thereof, to be licensed as a whole at no charge to all third
> parties under the terms of this License.

**Comment by matvore** [comment]
Correct, I have been instructed that, when distributed as compiled software, Werm needs to be licensed, as a whole, under the GPLv2 license. However, I have been instructed that individual source files within Werm that are not derived from GPLv2-licensed code do not need to be GPLv2-licensed, and that the Free Software Foundation expressly acknowledges BSD-3 material to be GPL-compatible per https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD
